### PR TITLE
Add 'config' as a entity_category

### PR DESCRIPTION
**Pull request by calisro**
Define the entity category per best practice from HA 2021.11+

### CODE REVIEW

**Comment by calisro** [comment]
https://developers.home-assistant.io/blog/2021/10/26/config-entity/#entity-categories

**Comment by nielsfaber** [comment]
I didn't know about the existence of such property, but I agree it is a good addition. thanks!

**Comment by crixionz** [comment]
I'm getting an error because a string is used instead of `EntityCategory`.
`Detected code that uses str (config) for entity category. This is deprecated and will stop working in Home Assistant 2022.4, it should be updated to use EntityCategory instead. Please report this issue.`

**Comment by calisro** [comment]
Yes but is it coming from this integration?

**Comment by crixionz** [comment]
Sorry, no I'm not sure!
I searched my custom_components folder for "category" and these four new lines were the only match. I saw the string "config" and assumed this must be what I was looking for.

However, now that you said that, I copy pasted some stuff and put these lines:
(yes, I have no clue what I'm doing here lol)
```python
from homeassistant.helpers.entity import ToggleEntity, EntityCategory
...
...
    @property
    def entity_category(self):
        """Return entity_category."""
        return EntityCategory.CONFIG
```
and restarted and I don't get any errors anymore 🤔

**Comment by crixionz** [comment]
I just noticed that the errors I got earlier didn't pop up right after restarting, so what I did there might be irrelevant. Stooopid me.

**Comment by calisro** [comment]
It actually is relevant.  I was just looking at it.  They want it enumerated now.  What you did is actually what I was looking at. lol  Its a simple fix.  That PR will make it easier to identify the offending code owners.

**Comment by crixionz** [comment]
Oh, lucky me! So the documentation you sent is outdated? They explicitly recommend a string for entity_category?

**Comment by calisro** [comment]
lol  that's exactly where I was going with this.  I think it is.  If we look here, we can see an example of the refactor?

https://github.com/home-assistant/core/pull/66379/commits/49a19fdab2d434cccb3100d9f999f96e0d767545

**Comment by crixionz** [comment]
Okay I have no clue what this should be telling me, I'm not a programmer at all, I'm just a dude looking at code and thinking about how I could steal it to fit me lol.

**Comment by calisro** [comment]
@nielsfaber I believe this is right?

 https://github.com/calisro/scheduler-component/commit/1b1c973a1cd1fc17ba02d12c26ee37b3a00b208d

**Comment by davet2001** [comment]
Yes this is correct.

You should now assign an entity category to 
E.g. `EntityCategory.CONFIG`.
Using `"config"` or `ENTITY_CATEGORY_CONFIG` anywhere will generate this warning.

We are trying to find a way of making the warning more helpful.

After the deprecation period, trying to assign the string will fail (at this point it will be very obvious where the problem is and probably easier to work out what to do).

**Comment by nielsfaber** [comment]
PR #182 is merged and will be part of the next release.
@calisro thanks for your efforts!

**Pull request merged**
