### PR TITLE
fix: Update switch.py

### LINKED ISSUE #388: STATE_ALARM_TRIGGERED was used from scheduler, this is a deprecated constant
The following is reported in the log file, after upgrading to HA 2024.11.0

### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
[What you expected to happen]
No error

### Actual behavior
[What actually happened]
error message produced...

```
Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 20:09:38 (1 occurrences)
Last logged: 20:09:38

STATE_ALARM_TRIGGERED was used from scheduler, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'scheduler' custom integration
```
### Steps to Reproduce
[Explain how to see the behaviour]

### PR DESCRIPTION
**Pull request by z-master42**
Fixes #388. 
Minimum HA version for this is 2024.11.

### CODE REVIEW

**Review by hacscred — COMMENTED** [review]
Adding backwards compatibility by inspecting the running version of Home Assistant, doesn't hurt. 

Someone _will_ install this on an older version and will wonder "why it doesn't work". Yes, those people should learn to read, but then again humanity is far from perfect. So, it's probably better to just add a conditional to avoid silly questions.

**Comment by nielsfaber** [comment]
Looks good to me, thanks!
@hacscred the hacs.json file contains the minimum required HA version for a certain release version, so backwards compatibility shouldn't be our concern.

**Comment by hacscred** [comment]
@nielsfaber People can install without using hacs. Such people are not imaginary as I am one of them. I have configured hacs, but I don't trust authors of custom components not to make mistakes at inconvenient times. 

Perhaps having such a file also means that Home Assistant reads the file when it loads and then fills the logs with errors or warnings when the versions don't match, but otherwise your plan won't work in general.

**Comment by z-master42** [comment]
I think the hacs.json tells HACS what the minimum HA version is for the integration to work. People with an older version of HA will therefore not be offered the update at all.

And people who install custom integrations manually without HACS should be smart enough to read changelogs and release notes to know if the integration will run with their HA version or not.

**Pull request merged**
