### PR TITLE
Use ha-blueprint

### PR DESCRIPTION
**Pull request by KTibow**
I recently announced ha-blueprint:
https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041?u=ktibow
This makes CI use it.

### CODE REVIEW

**Comment by KTibow** [comment]
Anything wrong with this?

**Comment by KTibow** [comment]
@nielsfaber sorry, but is there anything you have against this?

**Comment by KTibow** [comment]
So should I close this? I think it's a lot better than the current version.

**Comment by nielsfaber** [comment]
I don’t really know what it is and what the pro’s / cons would be.
As discussed (many times), I’m not really a fan of automations that cause merge conflicts and mess up the code.
I have black running in VScode now, thought it should be enough.

**Comment by KTibow** [comment]
I've disabled formatting and pushing now. I'm sorry about annoying you, I'll not do it in the future. Cons:
- Security-wise, you're relying on a 3rd party, which could steal stuff and whatever if it wanted to. But so goes for everything not made by you, which is pretty much everything.
- It uses some fancy stuff in order to trick hassfest into thinking it's being ran by GitHub Actions' runner, when it's being ran by a GitHub Action being ran by GitHub Actions' runner instead. It also might be a tad slower. But this isn't really an obstacle, as it still works just fine.
Pros:
- It constantly gets better, and every commit is tested before pushing it to the stable branch.
- It's still available to look through the source [if you want](https://github.com/KTibow/ha-blueprint).

I understand if it's tiring for you to maintain this project. I can help you with understanding it if you have questions.

**Comment by nielsfaber** [comment]
> I've disabled formatting and pushing now.

Oh, I thought that it's was all about that. 

> I'm sorry about annoying you, I'll not do it in the future. 

I'm not annoyed at all, I think its you who is more annoyed 😉 
You are talking to a total noob when it comes to Git and automating stuff.
Completely new here!
So I have no idea what the consequences are of merging this.
I was going to read into it, when i have the time... But I have a habit of being busy with many things at the same time.

> Security-wise, you're relying on a 3rd party, which could steal stuff and whatever if it wanted to. But so goes for everything not made by you, which is pretty much everything.

I have no idea what you mean here. Thought it installs something on my Git Repo. 
How is that an infringement?

> It uses some fancy stuff in order to trick hassfest into thinking it's being ran by GitHub Actions' runner, when it's being ran by a GitHub Action being ran by GitHub Actions' runner instead. It also might be a tad slower. But this isn't really an obstacle, as it still works just fine.

New to hassfest! I saw this is something checked for HACS compatibility.
Think I need it, that's all I know about it. 
I'm also working on another (alarm) integration, which I want to set up for HACS.
So I will read into this soon!

> It constantly gets better, and every commit is tested before pushing it to the stable branch.

I would like to know about the kind of test coverage.
Syntax errors already pop up in VScode..

> It's still available to look through the source if you want.
I understand if it's tiring for you to maintain this project. I can help you with understanding it if you have questions.

Think I need something like a noob manual to know what this is exactly.
Not sure if you should take the effort to write this though, because I don't know if i'm the average user for your project..
The real trouble here is that you are not talking to a software programmer..
I took a deep deep dive into understanding how HA works (and i could make my own stuff).
But these workflows would be yet another dive.. So you would have to take me by the hand a little bit, before making a PR.
I'm not blindly merging them because I had some experiences with the merge conflicts.

**Comment by KTibow** [comment]
> Oh, I thought that it's was all about that.

Well it runs checks as well (flake8 and HACS and hassfest)

> I'm not annoyed at all, I think its you who is more annoyed 😉

Thanks for pointing that out. You're definitely right. 😉

> I have no idea what you mean here. Thought it installs something on my Git Repo.
How is that an infringement?

If I wanted to make this malicious, then I could change the code, and then I could access free runtime and a GitHub token with push access. Of course, I have no such plans, unless a hacker hacks me in order to hack more.

> I would like to know about the kind of test coverage.
Syntax errors already pop up in VScode.

It runs wemake-python-styleguide, which helps give you ideas for how to make the style consistent with wemake-python-styleguide practices.

> Think I need something like a noob manual to know what this is exactly.
Not sure if you should take the effort to write this though, because I don't know if i'm the average user for your project..
The real trouble here is that you are not talking to a software programmer..
I took a deep deep dive into understanding how HA works (and i could make my own stuff).
But these workflows would be yet another dive.. So you would have to take me by the hand a little bit, before making a PR.
I'm not blindly merging them because I had some experiences with the merge conflicts.

Yeah, soon I want to document it more in the README.
As I said earlier:

> I've disabled formatting and pushing now.

**Comment by nielsfaber** [comment]
Could you check this problem:
https://github.com/nielsfaber/scheduler-card/runs/1351271727?check_suite_focus=true

This is basically why I am holding back on the CI stuff..
I only edited the readme file, and stuff breaks down. No idea what's going on.

**Comment by KTibow** [comment]
The HACS action is broken. Try switching to the new one:
https://github.com/marketplace/actions/hacs-action

**Pull request closed without merging**
