### PR TITLE
Patch a lot of stuff

### PR DESCRIPTION
**Pull request by KTibow**
Changes:
- CI
- Remove quotes
- Add black and remove pytest
- Add isort
- Formatting
- Docstrings
- Unnecessary stuff removed
- Add requirements.txt for testing

I worked **really hard on this!**

### CODE REVIEW

**Comment by KTibow** [comment]
The last test didn't pass because since this is a PR it didn't have permission.

**Comment by nielsfaber** [comment]
Hi @KTibow,

Could you take a look at the HACS validation script you added?
I keep getting reports that the validation fails, both for the card and for the component.

See for example:
https://github.com/nielsfaber/scheduler-component/runs/1142751368
```
AttributeError: type object 'HacsCore' has no attribute 'config_path'
```

I don't have any experience with these scripts, also I don't use HACS myself.
I am _really_ hoping that you can keep maintaining the HACS support for the component and integration.
Thanks 👍

**Comment by KTibow** [comment]
All of the HACS scripts are failing. This is the fault of HACS, they recently introduced a bug in their checker. Just remove it for now, and check again in a week or so. HACS will still gladly install it.

**Comment by nielsfaber** [comment]
OK clear, thanks.
Would it be possible to check only on making a new release? instead of every commit?
Would already drastically reduce amount of spam 😉

**Comment by KTibow** [comment]
Well then it might be too late for the bug to get caught... But you can change
```
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
```
to
```
on:
  release:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
```
(Also only triggers every Sunday instead of every day)

**Comment by KTibow** [comment]
BTW you should try out prereleases.

**Pull request merged**
