### PR TITLE
WIP: calculate length of each time slot (per action).

### PR DESCRIPTION
**Pull request by virgilm**
WIP, do not merge

Adds a []deltas array with length of each time slot. For now, it does not account for weekdays/weekends/sunrise/etc...

```
{
   "entity_id":"switch.schedule_b0c5e2",
   "state":"off",
   "attributes":{
      "entries":[
         "0DT0000T0800A0",
         "0DT0800T1600A1",
         "0DT1600T2000A2",
         "0DT2000T0000A0"
      ],
      "actions":[
         {
            "service":"set_value",
            "entity":"input_number.tariff",
            "value":0.01
         },
         {
            "service":"set_value",
            "entity":"input_number.tariff",
            "value":0.04
         },
         {
            "service":"set_value",
            "entity":"input_number.tariff",
            "value":0.13
         }
      ],
      "deltas":[
         480,
         480,
         240,
         240
      ],
      "friendly_name":"Schedule #b0c5e2",
      "icon":"mdi:calendar-clock"
   },
   "last_changed":"2020-10-07T20:17:27.210841+00:00",
   "last_updated":"2020-10-07T20:17:27.210841+00:00",
   "context":{
      "id":"1e76b31808da11ebaabb0fbd57b269c1",
      "parent_id":"None",
      "user_id":"ccefcf66bd5d45d892a16b90db5500e8"
   }
}
```

### CODE REVIEW

**Comment by nielsfaber** [comment]
???

**Comment by virgilm** [comment]
Sorry, I should not have made this a PR, I wrote about it https://community.home-assistant.io/t/scheduler-card-custom-component/217458/553. Feel free to discard, but I need some guidance on how to do this, happy to contribute to the project.

To re-iterate, I need to know upfront (say beginning of the day) how long a specific action would take (say, in 24h, my off peak rate lasts 8h).

The only way I found to do so is the code above, then I have some other code that associates the time slots with actions and summarizes them (e.g. adds time slots with the same action).

I know this is not generic enough for your component, and it might be of no interest to you, in which case I am going to live with my custom implementation. But if you have a way to do this in a generic way, I'd be happy to help write it.

**Comment by nielsfaber** [comment]
Nothing wrong with a little DIY hacking 👍 
But indeed I have my doubts whether this function has any added value for other people..
Are you aware that the start time and end time of each timeslot is already visible in the entity properties?
Take entry `0DT0800T1600A1`
It decodes as:
 - every day (`0D` = all days)
- starting from 08:00 (`T0800`)
- ending at 16:00 (`T1600`)
- execute action 1 (`A1`) -> which is in the actions array

Maybe it would be easier for you to make a script that interprets this attribute data and extracts duration from it?

**Comment by virgilm** [comment]
Ok, fair. Yeah, I figured that out, but I did not want to reinvent the wheel (parse the string that was created out of internal data), plus I was not clear what all possible values are. Thanks, I'll find some other solution I guess.

**Pull request closed without merging**
