### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by KTibow**
This cleans up some code that wasn't used. Flake8 told me about this.

### CODE REVIEW

**Comment by nielsfaber** [comment]
how did you detect the unused code?? 
That's genius! 
I wish I could see it in VS code..

**Comment by KTibow** [comment]
Just follow these instructions:
- Make sure Python is installed
- Remove flake8 extensions that might interfere or use a venv
- Install `wemake-python-styleguide` and `flake8` with pip
- Enable flake8 with the Python VSCode extension.

But I prefer the HTML view, with the instructions in #45.
image

**Comment by nielsfaber** [comment]
ooh that's flake8.
I have trouble with that since all HA dependencies are not found.
Had to disable it...
Capture6

**Comment by KTibow** [comment]
Weird. Flake8 shouldn't do that, the last time I checked you needed to enable a special plugin to get errors for dependencies not found.

**Comment by KTibow** [comment]
But you can always try #45 instead.

**Comment by nielsfaber** [comment]
got it working! very nice!
would be nice if it were more integrated with VS code, but i can definitely put this to use.
Thanks!

**Pull request merged**
